using DTasks.Configuration;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;

namespace DTasks.AspNetCore.Analyzer.Routing;

public class EndpointMappingGeneratorTests
{
    [Fact]
    public async Task MapAsyncGet_GeneratesCorrespondingExtensionMethod()
    {
        await RunTestAsync(
            source: """
                 endpoints.MapAsyncGet("pattern", async (
                     [FromServices] object arg1,
                     [FromBody] string arg2) =>
                 {
                     return 1;
                 });
                 """,
            method: """
                public static global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder MapAsyncGet(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder endpoints, global::System.String pattern, global::System.Func<global::System.Object, global::System.String, global::DTasks.DTask<global::System.Int32>> handler)
                {
                    return global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGet(endpoints, pattern, (global::Microsoft.AspNetCore.Http.HttpContext httpContext, [global::Microsoft.AspNetCore.Mvc.FromServicesAttribute] global::System.Object arg1, [global::Microsoft.AspNetCore.Mvc.FromBodyAttribute] global::System.String arg2) => global::Microsoft.AspNetCore.Http.DTasksHttpContextExtensions.RunAsync(httpContext, handler(arg1, arg2)));
                }
                """);
    }
    
    private static async Task RunTestAsync(string source, string method)
    {
        source = $"""
            using Microsoft.AspNetCore.Mvc;
            using Microsoft.AspNetCore.Routing;
            
            IEndpointRouteBuilder endpoints = null!;
            
            {source}
            """;

        method = string.Join(Environment.NewLine, method.Split(Environment.NewLine)
            .Select(line => $"    {line}"));
        
        string expected = $$"""
            // <auto-generated />
            
            namespace Microsoft.AspNetCore.Routing;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DTasks.AspNetCore.Analyzer", "0.4.0.0")]
            internal static class DTasksEndpointBuilderExtensions
            {
            {{method}}
            }
            """;
        
        var test = new CSharpSourceGeneratorTest<EndpointMappingGenerator, DefaultVerifier>
        {
            ReferenceAssemblies = ReferenceAssemblies.Net.Net90,
            TestState =
            {
                OutputKind = OutputKind.ConsoleApplication,
                Sources = { source },
                GeneratedSources =
                {
                    (typeof(EndpointMappingGenerator), "DTasks.AspNetCore.Analyzer.Routing.g.cs", expected)
                },
                AdditionalReferences =
                {
                    typeof(IEndpointRouteBuilder).Assembly,
                    typeof(IEndpointConventionBuilder).Assembly,
                    typeof(FromServicesAttribute).Assembly,
                    typeof(DTask).Assembly,
                    typeof(AspNetCoreCoreDTasksConfigurationBuilderExtensions).Assembly,
                    typeof(AspNetCoreDTasksConfigurationBuilderExtensions).Assembly
                }
            }
        };
        
        await test.RunAsync();
    }
}