using DTasks.Configuration;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;

namespace DTasks.Analyzer;

public class DTasksGeneratorTests
{
    [Fact]
    public async Task GenericDTaskLocalInDAsyncMethod_ProducesCallToSurrogateDTaskOf()
    {
        await RunTestAsync(
            source: """
                static class C
                {
                    static async DTask M()
                    {
                        DTask<int> t = null!;
                    }
                }
                """,
            expectedInfrastructureInvocations: """
                SurrogateDTaskOf<global::System.Int32>()
                """);
    }
    
    [Fact]
    public async Task GenericDTaskParameterInDAsyncMethod_ProducesCallToSurrogateDTaskOf()
    {
        await RunTestAsync(
            source: """
                static class C
                {
                    static async DTask M(DTask<int> t)
                    {
                    }
                }
                """,
            expectedInfrastructureInvocations: """
                SurrogateDTaskOf<global::System.Int32>()
                """);
    }
    
    [Fact]
    public async Task CallToGenericWhenAll_ProducesCallToAwaitWhenAllOf()
    {
        await RunTestAsync(
            source: """
                static class C
                {
                    static void M()
                    {
                        DTask.WhenAll((DTask<int>)null);
                    }
                }
                """,
            expectedInfrastructureInvocations: """
                AwaitWhenAllOf<global::System.Int32>()
                """);
    }
    
    [Fact]
    public async Task GenericDTaskLocalAndCallToGenericWhenAllInDAsyncMethod_ProducesCallToSurrogateDTaskOfAndToAwaitWhenAllOf()
    {
        await RunTestAsync(
            source: """
                static class C
                {
                    static async DTask M()
                    {
                        DTask<int> t = null!;
                        DTask.WhenAll(t);
                    }
                }
                """,
            expectedInfrastructureInvocations: """
                SurrogateDTaskOf<global::System.Int32>()
                AwaitWhenAllOf<global::System.Int32>()
                """);
    }
    
    [Fact]
    public async Task NonGenericDTaskLocalInDAsyncMethod_ProducesNoCalls()
    {
        await RunTestAsync(
            source: """
                static class C
                {
                    static async DTask M()
                    {
                        DTask t = null!;
                    }
                }
                """,
            expectedInfrastructureInvocations: "");
    }
    
    [Fact]
    public async Task GenericDTaskLocalInNonAsyncMethod_ProducesNoCalls()
    {
        await RunTestAsync(
            source: """
                static class C
                {
                    static void M()
                    {
                        DTask<int> t = null!;
                    }
                }
                """,
            expectedInfrastructureInvocations: "");
    }

    private static async Task RunTestAsync(string source, string expectedInfrastructureInvocations)
    {
        source = $"""
            using DTasks;
            
            namespace DTasks.Analyzer.Tests;
            
            {source}
            """;
        
        string infrastructureBuilderInvocations = expectedInfrastructureInvocations == string.Empty
            ? string.Empty
            : string.Concat(expectedInfrastructureInvocations
                .Split(Environment.NewLine)
                .Select(invocation => $"{Environment.NewLine}                infrastructure.{invocation};"));
            
        string expected = $$"""
            // <auto-generated />
            
            namespace DTasks.Configuration;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DTasks.Analyzer", "0.4.0.0")]
            internal static class DefaultDTasksConfigurationBuilderExtensions
            {
                public static TBuilder AutoConfigure<TBuilder>(this TBuilder builder)
                    where TBuilder : global::DTasks.Configuration.IDTasksConfigurationBuilder
                {
                    builder.ConfigureMarshaling(marshaling =>
                    {
                        marshaling.RegisterDAsyncMethods(typeof(DefaultDTasksConfigurationBuilderExtensions).Assembly);
                        marshaling.ConfigureInfrastructure(infrastructure =>
                        {{{infrastructureBuilderInvocations}}
                        });
                    });
                    return builder;
                }
            }
            """;
        
        var test = new CSharpSourceGeneratorTest<DTasksGenerator, DefaultVerifier>
        {
            ReferenceAssemblies = ReferenceAssemblies.Net.Net90,
            TestState =
            {
                Sources = { source },
                GeneratedSources =
                {
                    (typeof(DTasksGenerator), "DTasks.Analyzer.g.cs", expected)
                },
                AdditionalReferences = { typeof(DTask).Assembly, typeof(DTasksConfiguration).Assembly }
            }
        };
        
        await test.RunAsync();
    }
}