using System.Collections.Immutable;
using System.Text;

namespace DTasks.Tests.Interceptors.Emit;

internal static class ILGeneratorInterceptorsRenderer
{
    public static void Render(StringBuilder source, ImmutableArray<InterceptionLocationInfo> locations)
    {
        source.AppendLine("""
            // <auto-generated />

            #nullable enable

            namespace System.Runtime.CompilerServices
            {
                using System.Diagnostics.CodeAnalysis;

            #pragma warning disable CS9113 // Parameter is unread.
                [ExcludeFromCodeCoverage]
                [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
                file sealed class InterceptsLocationAttribute(string filePath, int line, int character) : Attribute;
            #pragma warning restore CS9113 // Parameter is unread.
            }

            namespace DTasks.Generated.Emit
            {
                using System.Diagnostics;
                using System.Diagnostics.CodeAnalysis;
                using System.Reflection;
                using System.Reflection.Emit;
                using System.Runtime.CompilerServices;
                using System.Runtime.InteropServices;
            
                [ExcludeFromCodeCoverage]
                public static class ILGeneratorInterceptors
                {
                    private static readonly ThreadLocal<ILGenerator?> s_interceptorLocal = new();
                
                    public static IDisposable InterceptCalls(this ILGenerator il)
                    {
                        Debug.Assert(s_interceptorLocal.Value is null);
                        
                        s_interceptorLocal.Value = il;
                        return new InterceptionScope(il);
                    }
                
                    private class InterceptionScope(ILGenerator il) : IDisposable
                    {
                        void IDisposable.Dispose()
                        {
                            Debug.Assert(ReferenceEquals(il, s_interceptorLocal.Value));
                            
                            s_interceptorLocal.Value = null;
                        }
                    }
            """);

        foreach (var location in locations)
        {
            source.AppendLine();
            source
                .Append("        [InterceptsLocationAttribute(@\"")
                .Append(location.FilePath)
                .Append("\", ")
                .Append(location.Line)
                .Append(", ")
                .Append(location.Character)
                .AppendLine(")]");
        }

        source.AppendLine("""
                    public static ILGenerator GetILGenerator(this MethodBuilder method)
                    {
                        ILGenerator il = method.GetILGenerator();
                        if (s_interceptorLocal.Value is not ILGenerator interceptor)
                            return il;

                        il.Emit(OpCodes.Ret);
                        return interceptor;
                    }
                }
            }
            """);
    }
}