services:
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    restart: unless-stopped
    command: "azurite --blobHost 0.0.0.0 --loose"
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - azurite_data:/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  azurite_data:
  redis_data: