name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        configuration:
          - Debug-Tests
          - Release-Tests
        dotnet-version:
          - net8.0
          - net9.0

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x
      
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build ${{ matrix.dotnet-version }} ${{ matrix.configuration }}
        run: dotnet build --no-restore

      - name: Test ${{ matrix.dotnet-version }} ${{ matrix.configuration }}
        run: dotnet test -f ${{ matrix.dotnet-version }} -c ${{ matrix.configuration }} --no-build --no-restore --verbosity normal --logger trx --results-directory ${{ matrix.configuration }}/${{ matrix.dotnet-version }}/TestResults

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ${{ matrix.configuration }}/${{ matrix.dotnet-version }}/TestResults/**/*.xml
            ${{ matrix.configuration }}/${{ matrix.dotnet-version }}/TestResults/**/*.trx
            ${{ matrix.configuration }}/${{ matrix.dotnet-version }}/TestResults/**/*.json
