name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        configuration:
          - Debug-Tests
          - Release-Tests
        dotnet-version:
          # - net6.0
          - net8.0
          # - net9.0

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            8.x
            9.x
      
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Remove DTasks.Tests.Interceptors from solution
        run: dotnet sln remove tests/DTasks.Tests.Interceptors/DTasks.Tests.Interceptors.csproj
      
      - name: Build DTasks.Tests.Interceptors
        run: dotnet build tests/DTasks.Tests.Interceptors/DTasks.Tests.Interceptors.csproj --no-restore

      - name: Build ${{ matrix.dotnet-version }} ${{ matrix.configuration }}
        run: dotnet build -c ${{ matrix.configuration }} --no-restore

      - name: Add DTasks.Tests.Interceptors to solution
        run: dotnet sln add tests/DTasks.Tests.Interceptors/DTasks.Tests.Interceptors.csproj
      
      - name: Test ${{ matrix.dotnet-version }} ${{ matrix.configuration }} 1
        run: dotnet test tests/DTasks.Extensions.DependencyInjection.Tests/DTasks.Extensions.DependencyInjection.Tests.csproj -f ${{ matrix.dotnet-version }} -c ${{ matrix.configuration }} --no-build --no-restore --verbosity normal --logger trx --results-directory ${{ matrix.configuration }}/${{ matrix.dotnet-version }}/TestResults

      - name: Test ${{ matrix.dotnet-version }} ${{ matrix.configuration }} 2
        run: dotnet test tests/DTasks.Extensions.Hosting.Tests/DTasks.Extensions.Hosting.Tests.csproj -f ${{ matrix.dotnet-version }} -c ${{ matrix.configuration }} --no-build --no-restore --verbosity normal --logger trx --results-directory ${{ matrix.configuration }}/${{ matrix.dotnet-version }}/TestResults

      - name: Test ${{ matrix.dotnet-version }} ${{ matrix.configuration }} 3
        run: dotnet test tests/DTasks.Inspection.Dynamic.Tests/DTasks.Inspection.Dynamic.Tests.csproj -f ${{ matrix.dotnet-version }} -c ${{ matrix.configuration }} --no-build --no-restore --verbosity normal --logger trx --results-directory ${{ matrix.configuration }}/${{ matrix.dotnet-version }}/TestResults

      - name: Test ${{ matrix.dotnet-version }} ${{ matrix.configuration }} 4
        run: dotnet test tests/DTasks.Serialization.Json.Tests/DTasks.Serialization.Json.Tests.csproj -f ${{ matrix.dotnet-version }} -c ${{ matrix.configuration }} --no-build --no-restore --verbosity normal --logger trx --results-directory ${{ matrix.configuration }}/${{ matrix.dotnet-version }}/TestResults

      - name: Test ${{ matrix.dotnet-version }} ${{ matrix.configuration }} 5
        run: dotnet test tests/DTasks.Serialization.StackExchangeRedis.Tests/DTasks.Serialization.StackExchangeRedis.Tests.csproj -f ${{ matrix.dotnet-version }} -c ${{ matrix.configuration }} --no-build --no-restore --verbosity normal --logger trx --results-directory ${{ matrix.configuration }}/${{ matrix.dotnet-version }}/TestResults

      - name: Test ${{ matrix.dotnet-version }} ${{ matrix.configuration }} 6
        run: dotnet test tests/DTasks.Tests/DTasks.Tests.csproj -f ${{ matrix.dotnet-version }} -c ${{ matrix.configuration }} --no-build --no-restore --verbosity normal --logger trx --results-directory ${{ matrix.configuration }}/${{ matrix.dotnet-version }}/TestResults

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ${{ matrix.configuration }}/${{ matrix.dotnet-version }}/TestResults/**/*.xml
            ${{ matrix.configuration }}/${{ matrix.dotnet-version }}/TestResults/**/*.trx
            ${{ matrix.configuration }}/${{ matrix.dotnet-version }}/TestResults/**/*.json
