name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        configuration:
          - Debug-Tests
          - Release-Tests
        dotnet-version:
          - net6.0
          - net8.0
          - net9.0

    steps:
      - uses: actions/checkout@v4
      
      - name: dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            8.x
            9.x
      
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Remove DTasks.Tests.Interceptors from solution
        run: dotnet sln remove tests/DTasks.Tests.Interceptors/DTasks.Tests.Interceptors.csproj
      
      - name: Build DTasks.Tests.Interceptors
        run: dotnet build tests/DTasks.Tests.Interceptors/DTasks.Tests.Interceptors.csproj --no-restore

      - name: Build ${{ matrix.dotnet-version }} ${{ matrix.configuration }}
        run: dotnet build -c ${{ matrix.configuration }} --no-restore

      - name: Test ${{ matrix.dotnet-version }} ${{ matrix.configuration }}
        run: dotnet test -f ${{ matrix.dotnet-version }} -c ${{ matrix.configuration }} --no-build --no-restore --verbosity normal --logger trx --results-directory TestResults

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.dotnet-version }}-${{ matrix.configuration }}
          path: TestResults
