name: Release

on:
  pull_request:
    branches:
      - main
  # release:
  #   types:
  #     - published
  #     - prereleased

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Get version
        id: get_version
        run: |
          echo "VERSION=0.0.1" >> $GITHUB_ENV
          echo "Version: $VERSION"
          
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            8.x
            9.x
          
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build -c Release --no-restore -p:Version=${VERSION#v}

      - name: Pack
        run: dotnet pack -c Release --output nupkgs -p:PackageVersion=${VERSION#v}

      # - name: Publish to NuGet
      #   run: dotnet nuget push "nupkgs/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate